#!/bin/bash
#set job requirement
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --cpus-per-task=4
#SBATCH --time=06:00:00
#SBATCH --output=train-%A.out
#SBATCH --error=train-%A.err

module purge
module load 2022
module load Anaconda3/2022.05

conda env create -f  training/environment.yml

source activate supervised-learning

pip install opencv-python
pip install torchvision


python training/supervised-learning/train.py